services:
  db:
    image: 'postgres:14-alpine'
    container_name: postgresql-container
    environment:
      POSTGRES_DB: escuela-tecnica-test
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
#    volumes: #volumenes permite guardar datos del contenedor
#      - 'db-data:/var/lib/postgresql/data'

  backend:
#    build: .
    image: 'luchonoprograma/escuela_tecnica-backend:latest'
    container_name: escuela-tecnica-container
    ports:
      - '9090:9090' #1er puerto antes de : es host de la maquina de docker; # 2do puerto despues de : es puerto dentro del contenedor docker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/escuela-tecnica-test #el host db hace referencia al nombre del servicio db
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
    depends_on:
      - db